#!/bin/bash -u
{ set +x; } 2>/dev/null #Suppresses echoing every line
SOURCE=$0
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
ROOTDIR=$(cd $DIR && cd ../ && pwd)

if which brew > /dev/null
then
    echo "brew is installed, skipping…"
else
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew list docfx || brew install docfx

pushd $ROOTDIR >/dev/null 2>&1

ABBOT_DIR="../abbot"

if [ ! -d $ABBOT_DIR ] 
then
    echo "Directory $ABBOT_DIR does not exist."
else
    echo "aseriousbiz/abbot exists in sibling directory. ✓"
fi

ABBOT_PY_DOCS_DIR="../abbot-py-docs"

if [ ! -d $ABBOT_PY_DOCS_DIR ] 
then
    echo "Directory $ABBOT_PY_DOCS_DIR does not exist. Cloning..."
    pushd ../
    git clone https://github.com/aseriousbiz/abbot-py-docs
    popd
else
    echo "aseriousbiz/abbot-py-docs exists in sibling directory. ✓"
fi

ABBOT_JS_DIR="../abbot-js"

if [ ! -d $ABBOT_JS_DIR ] 
then
    echo "Directory $ABBOT_JS_DIR does not exist. Cloning..."
    pushd ../
    git clone https://github.com/aseriousbiz/abbot-js
    popd
else
    echo "aseriousbiz/abbot-js exists in sibling directory. ✓"
fi

popd >/dev/null 2>&1

echo "Run script/build to build it and then script/server to run it locally"