#!/bin/bash -u
{ set +x; } 2>/dev/null #Suppresses echoing every line
SOURCE=$0
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
ROOTDIR=$(cd $DIR && cd ../ && pwd)
PARENTDIR=$(cd $ROOTDIR && cd ../ && pwd)
cd "$ROOTDIR"

while (( "$#" )); do
  case "$1" in
    --trace)
      { set -x; } 2>/dev/null
    ;;
    -*|--*=) # unsupported flags
      echo "./build [--trace]" >&2
      exit 0
    ;;
  esac
  shift
done

ABBOTJSDIR="$PARENTDIR/abbot-js"
if [ ! -d $ABBOTJSDIR ]
then
    echo "Can't find abbot-js in $ABBOTJSDIR" 1>&2
    echo "Please run script/bootstrap first before building" 1>&2
else
    echo "*** Building abbot-js ***"
    (
      cd "$ABBOTJSDIR"
      script/build
      node "$ROOTDIR/node_modules/node2docfx/node2docfx.js" "$ABBOTJSDIR/node2docfx.json"
      cp -R ./out ${ROOTDIR}/src/reference/javascript
    )
fi

ABBOTPYDIR="$PARENTDIR/abbot-py-docs"
if [ ! -d $ABBOTPYDIR ]
then
    echo "Can't find abbot-py-docs in $ABBOTPYDIR" 1>&2
    echo "Please run script/bootstrap first before building" 1>&2
else
    echo "*** Building abbot-py-docs ***"
    (
      rm -Rf "$ROOTDIR/src/reference/python"
      cd "$ABBOTPYDIR"
      cp -R _build/html/docfx_yaml/ "${ROOTDIR}/src/reference/python"
      cp _static/toc.yml "${ROOTDIR}/src/reference/python"
    )
fi

ABBOTCSDIR="$PARENTDIR/abbot"
if [ ! -d $ABBOTCSDIR ]
then
    echo "Can't find abbot in $ABBOTCSDIR" 1>&2
    echo "Please run script/bootstrap first before building" 1>&2
else
    echo "*** Building abbot ***"
    (
      cd "$ABBOTCSDIR"
      dotnet build src/scripting/Abbot.Scripting.Interfaces/Abbot.Scripting.Interfaces.csproj --configuration Release -o "${ROOTDIR}/_build"
    )
fi

