#!/bin/bash -u
{ set +x; } 2>/dev/null #Suppresses echoing every line
SOURCE=$0
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
ROOTDIR=$(cd $DIR && cd ../ && pwd)
pushd $ROOTDIR
npm run build